package com.fdmgroup.servletdemos.controller;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.fdmgroup.servletdemos.dao.IStorange;
import com.fdmgroup.servletdemos.dao.ListDao;
import com.fdmgroup.servletdemos.model.Student;

/**
 * Servlet implementation class AddStudentServlet
 */
public class AddStudentServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
    
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
	}
	
	protected void doPost(HttpServletRequest request, HttpServletResponse resp) throws ServletException, IOException {
		
		//Parameter - data from the client , Attribute -data generated by code++
		//Parameter - String to String  mapping
		
	
		
		int id = Integer.parseInt(request.getParameter("id"));
		String name = request.getParameter("name");
		String phone =request.getParameter("phone");
		
		
		
		
		
		if(name.equalsIgnoreCase("blah")) {
			resp.sendRedirect("https://www.google.com/search?q=blah");
		}
		//else if(name.trim().length()<2) {
		//	String alert = "name to short";
		//	request .setAttribute("myAlert", alert);
		//	RequestDispatcher dispatcher = request.getRequestDispatcher("confirmationServlet");
		//	dispatcher.forward(request, resp);
//			
//		}
//		else {
//		PrintWriter out = resp.getWriter();
//		out.println("<html>");
//		out.println("<head><title> Student List</title></head>");
//		out.println("<body>");
//		out.println("<p>Student" +id+"</p>");
//		out.println("<p>Student" +name+"</p>");
//		out.println("<p>Student" +phone+"</p>");
//		out.println("<a href=\"home.html\"> home</a>");
//		out.println("</body>");
//		out.println("</html>");
//		}
		
		Student student = new Student(id,name,phone);
		//Student student = null;
		IStorange dao = new ListDao();
		boolean added = dao.create(student);
		
		request.setAttribute("added", added);
		RequestDispatcher dispatcher = request.getRequestDispatcher("confirmationServlet");
		dispatcher.forward(request, resp);
		
	}

}
